version: '3.8'
services:
  mariadb:
    build: ${MARIADB_DIR}
    image: ${IMG_MARIADB_NAME}
    container_name: ${CON_MARIADB_NAME}
    restart: always
    env_file: .env 
    networks: 
      - net-inception
    ports: 
      - '3306'
    volumes:
      - vol-DB:${MARIADB_DATA_DIR}
  wordpress:
    depends_on:
      - mariadb
    build: ${WORDPRESS_DIR}
    image: ${IMG_WORDPRESS_NAME}
    container_name: ${CON_WORDPRESS_NAME}
    restart: always
    env_file: .env 
    networks: 
      - net-inception
    ports: 
      - '9000'
    volumes:
      - vol-WordPress:${WORDPRESS_DATA_DIR}
  nginx:
    depends_on:
      - wordpress
      - mariadb
    build: ${NGINX_DIR}
    image: ${IMG_NGINX_NAME}
    container_name: ${CON_NGINX_NAME}
    restart: always
    env_file: .env 
    networks: 
      - net-inception
    ports: 
      - '443:443'
    volumes:
      - vol-WordPress:${NGINX_DATA_DIR}

networks: 
  net-inception:
    driver: bridge
    name: net-inception

volumes:
  vol-DB:
    driver: local
    driver_opts:
      device: ${VOLUMES_DIR}/DB
      o: bind
      type: none
    name: vol-DB
  vol-WordPress:
    driver: local
    driver_opts:
      device: ${VOLUMES_DIR}/WordPress
      o: bind
      type: none
    name: vol-WordPress
